

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "8501:8501"
    volumes:
      - ./src/frontend:/app
    depends_on:
      - backend
    restart: always
