version: '3.8'

services:
  backend:
    container_name: fastapi_backend
    build:
      context: .
      dockerfile: src/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    container_name: streamlit_frontend
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./src/frontend:/app
    depends_on:
      - backend
    command: streamlit run Home.py --server.port 8501 --server.address 0.0.0.0