site_name: RelatAI - Relatórios Inteligentes com dados IPEA
site_url: https://unb-mds.github.io/2025-1-RelatAI
use_directory_urls: true         

site_description: Documentação oficial do projeto
site_author: Sua Equipe
theme:
  name: material
  logo: mkdocs/images/iconegrafico.png
  favicon: mkdocs/images/iconegrafico.png
  palette:
    - scheme: default
      primary: blue 
      accent: red
      toggle:
        icon: material/brightness-4
        name: Modo escuro
    - scheme: slate
      primary: blue 
      accent: red
      toggle:
        icon: material/brightness-7
        name: Modo claro
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.tabs.link
    - content.action.edit
extra_css:
  - mkdocs/stylesheets/extra.css
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.tasklist

nav:
  - Home: index.md
  - Documento de Arquitetura: mkdocs/docarquitetura.md
  - Requisitos: sprints/requisitos.md
  - Sprint 0: sprints/sprint-0.md
  - Sprint 1: sprints/sprint-1.md
  - Sprint 2: sprints/sprint-2.md
  - Sprint 3: sprints/sprint-3.md
  - Sprint 4: sprints/sprint-4.md
  - Sprint 5: sprints/sprint-5.md
  - Sprint 6: sprints/sprint-6.md

  
